package §6V§
{
   import flash.utils.Dictionary;
   
   public class §4"7§
   {
      
      private static var §-#=§:§4"7§;
       
      
      private var §3?§:Dictionary;
      
      public function §4"7§()
      {
         this.§3?§ = new Dictionary();
         super();
         this.§3?§["AF"] = "AFGHANISTAN";
         this.§3?§["AX"] = "ÅLAND ISLANDS";
         this.§3?§["AL"] = "ALBANIA";
         this.§3?§["DZ"] = "ALGERIA";
         this.§3?§["AS"] = "AMERICAN SAMOA";
         this.§3?§["AD"] = "ANDORRA";
         this.§3?§["AO"] = "ANGOLA";
         this.§3?§["AI"] = "ANGUILLA";
         this.§3?§["AQ"] = "ANTARCTICA";
         this.§3?§["AG"] = "ANTIGUA AND BARBUDA";
         this.§3?§["AR"] = "ARGENTINA";
         this.§3?§["AM"] = "ARMENIA";
         this.§3?§["AW"] = "ARUBA";
         this.§3?§["AU"] = "AUSTRALIA";
         this.§3?§["AT"] = "AUSTRIA";
         this.§3?§["AZ"] = "AZERBAIJAN";
         this.§3?§["BS"] = "BAHAMAS";
         this.§3?§["BH"] = "BAHRAIN";
         this.§3?§["BD"] = "BANGLADESH";
         this.§3?§["BB"] = "BARBADOS";
         this.§3?§["BY"] = "BELARUS";
         this.§3?§["BE"] = "BELGIUM";
         this.§3?§["BZ"] = "BELIZE";
         this.§3?§["BJ"] = "BENIN";
         this.§3?§["BM"] = "BERMUDA";
         this.§3?§["BT"] = "BHUTAN";
         this.§3?§["BO"] = "BOLIVIA, PLURINATIONAL STATE OF";
         this.§3?§["BQ"] = "BONAIRE, SINT EUSTATIUS AND SABA";
         this.§3?§["BA"] = "BOSNIA AND HERZEGOVINA";
         this.§3?§["BW"] = "BOTSWANA";
         this.§3?§["BV"] = "BOUVET ISLAND";
         this.§3?§["BR"] = "BRAZIL";
         this.§3?§["IO"] = "BRITISH INDIAN OCEAN TERRITORY";
         this.§3?§["BN"] = "BRUNEI DARUSSALAM";
         this.§3?§["BG"] = "BULGARIA";
         this.§3?§["BF"] = "BURKINA FASO";
         this.§3?§["BI"] = "BURUNDI";
         this.§3?§["KH"] = "CAMBODIA";
         this.§3?§["CM"] = "CAMEROON";
         this.§3?§["CA"] = "CANADA";
         this.§3?§["CV"] = "CAPE VERDE";
         this.§3?§["KY"] = "CAYMAN ISLANDS";
         this.§3?§["CF"] = "CENTRAL AFRICAN REPUBLIC";
         this.§3?§["TD"] = "CHAD";
         this.§3?§["CL"] = "CHILE";
         this.§3?§["CN"] = "CHINA";
         this.§3?§["CX"] = "CHRISTMAS ISLAND";
         this.§3?§["CC"] = "COCOS (KEELING) ISLANDS";
         this.§3?§["CO"] = "COLOMBIA";
         this.§3?§["KM"] = "COMOROS";
         this.§3?§["CG"] = "CONGO";
         this.§3?§["CD"] = "CONGO, THE DEMOCRATIC REPUBLIC OF THE";
         this.§3?§["CK"] = "COOK ISLANDS";
         this.§3?§["CR"] = "COSTA RICA";
         this.§3?§["CI"] = "CÔTE D\'IVOIRE";
         this.§3?§["HR"] = "CROATIA";
         this.§3?§["CU"] = "CUBA";
         this.§3?§["CW"] = "CURAÇAO";
         this.§3?§["CY"] = "CYPRUS";
         this.§3?§["CZ"] = "CZECH REPUBLIC";
         this.§3?§["DK"] = "DENMARK";
         this.§3?§["DJ"] = "DJIBOUTI";
         this.§3?§["DM"] = "DOMINICA";
         this.§3?§["DO"] = "DOMINICAN REPUBLIC";
         this.§3?§["EC"] = "ECUADOR";
         this.§3?§["EG"] = "EGYPT";
         this.§3?§["SV"] = "EL SALVADOR";
         this.§3?§["GQ"] = "EQUATORIAL GUINEA";
         this.§3?§["ER"] = "ERITREA";
         this.§3?§["EE"] = "ESTONIA";
         this.§3?§["ET"] = "ETHIOPIA";
         this.§3?§["FK"] = "FALKLAND ISLANDS (MALVINAS)";
         this.§3?§["FO"] = "FAROE ISLANDS";
         this.§3?§["FJ"] = "FIJI";
         this.§3?§["FI"] = "FINLAND";
         this.§3?§["FR"] = "FRANCE";
         this.§3?§["GF"] = "FRENCH GUIANA";
         this.§3?§["PF"] = "FRENCH POLYNESIA";
         this.§3?§["TF"] = "FRENCH SOUTHERN TERRITORIES";
         this.§3?§["GA"] = "GABON";
         this.§3?§["GM"] = "GAMBIA";
         this.§3?§["GE"] = "GEORGIA";
         this.§3?§["DE"] = "GERMANY";
         this.§3?§["GH"] = "GHANA";
         this.§3?§["GI"] = "GIBRALTAR";
         this.§3?§["GR"] = "GREECE";
         this.§3?§["GL"] = "GREENLAND";
         this.§3?§["GD"] = "GRENADA";
         this.§3?§["GP"] = "GUADELOUPE";
         this.§3?§["GU"] = "GUAM";
         this.§3?§["GT"] = "GUATEMALA";
         this.§3?§["GG"] = "GUERNSEY";
         this.§3?§["GN"] = "GUINEA";
         this.§3?§["GW"] = "GUINEA-BISSAU";
         this.§3?§["GY"] = "GUYANA";
         this.§3?§["HT"] = "HAITI";
         this.§3?§["HM"] = "HEARD ISLAND AND MCDONALD ISLANDS";
         this.§3?§["VA"] = "HOLY SEE (VATICAN CITY STATE)";
         this.§3?§["HN"] = "HONDURAS";
         this.§3?§["HK"] = "HONG KONG";
         this.§3?§["HU"] = "HUNGARY";
         this.§3?§["IS"] = "ICELAND";
         this.§3?§["IN"] = "INDIA";
         this.§3?§["ID"] = "INDONESIA";
         this.§3?§["IR"] = "IRAN, ISLAMIC REPUBLIC OF";
         this.§3?§["IQ"] = "IRAQ";
         this.§3?§["IE"] = "IRELAND";
         this.§3?§["IM"] = "ISLE OF MAN";
         this.§3?§["IL"] = "ISRAEL";
         this.§3?§["IT"] = "ITALY";
         this.§3?§["JM"] = "JAMAICA";
         this.§3?§["JP"] = "JAPAN";
         this.§3?§["JE"] = "JERSEY";
         this.§3?§["JO"] = "JORDAN";
         this.§3?§["KZ"] = "KAZAKHSTAN";
         this.§3?§["KE"] = "KENYA";
         this.§3?§["KI"] = "KIRIBATI";
         this.§3?§["KP"] = "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF";
         this.§3?§["KR"] = "KOREA, REPUBLIC OF";
         this.§3?§["KW"] = "KUWAIT";
         this.§3?§["KG"] = "KYRGYZSTAN";
         this.§3?§["LA"] = "LAO PEOPLE\'S DEMOCRATIC REPUBLIC";
         this.§3?§["LV"] = "LATVIA";
         this.§3?§["LB"] = "LEBANON";
         this.§3?§["LS"] = "LESOTHO";
         this.§3?§["LR"] = "LIBERIA";
         this.§3?§["LY"] = "LIBYA";
         this.§3?§["LI"] = "LIECHTENSTEIN";
         this.§3?§["LT"] = "LITHUANIA";
         this.§3?§["LU"] = "LUXEMBOURG";
         this.§3?§["MO"] = "MACAO";
         this.§3?§["MK"] = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF";
         this.§3?§["MG"] = "MADAGASCAR";
         this.§3?§["MW"] = "MALAWI";
         this.§3?§["MY"] = "MALAYSIA";
         this.§3?§["MV"] = "MALDIVES";
         this.§3?§["ML"] = "MALI";
         this.§3?§["MT"] = "MALTA";
         this.§3?§["MH"] = "MARSHALL ISLANDS";
         this.§3?§["MQ"] = "MARTINIQUE";
         this.§3?§["MR"] = "MAURITANIA";
         this.§3?§["MU"] = "MAURITIUS";
         this.§3?§["YT"] = "MAYOTTE";
         this.§3?§["MX"] = "MEXICO";
         this.§3?§["FM"] = "MICRONESIA, FEDERATED STATES OF";
         this.§3?§["MD"] = "MOLDOVA, REPUBLIC OF";
         this.§3?§["MC"] = "MONACO";
         this.§3?§["MN"] = "MONGOLIA";
         this.§3?§["ME"] = "MONTENEGRO";
         this.§3?§["MS"] = "MONTSERRAT";
         this.§3?§["MA"] = "MOROCCO";
         this.§3?§["MZ"] = "MOZAMBIQUE";
         this.§3?§["MM"] = "MYANMAR";
         this.§3?§["NA"] = "NAMIBIA";
         this.§3?§["NR"] = "NAURU";
         this.§3?§["NP"] = "NEPAL";
         this.§3?§["NL"] = "NETHERLANDS";
         this.§3?§["NC"] = "NEW CALEDONIA";
         this.§3?§["NZ"] = "NEW ZEALAND";
         this.§3?§["NI"] = "NICARAGUA";
         this.§3?§["NE"] = "NIGER";
         this.§3?§["NG"] = "NIGERIA";
         this.§3?§["NU"] = "NIUE";
         this.§3?§["NF"] = "NORFOLK ISLAND";
         this.§3?§["MP"] = "NORTHERN MARIANA ISLANDS";
         this.§3?§["NO"] = "NORWAY";
         this.§3?§["OM"] = "OMAN";
         this.§3?§["PK"] = "PAKISTAN";
         this.§3?§["PW"] = "PALAU";
         this.§3?§["PS"] = "PALESTINE, STATE OF";
         this.§3?§["PA"] = "PANAMA";
         this.§3?§["PG"] = "PAPUA NEW GUINEA";
         this.§3?§["PY"] = "PARAGUAY";
         this.§3?§["PE"] = "PERU";
         this.§3?§["PH"] = "PHILIPPINES";
         this.§3?§["PN"] = "PITCAIRN";
         this.§3?§["PL"] = "POLAND";
         this.§3?§["PT"] = "PORTUGAL";
         this.§3?§["PR"] = "PUERTO RICO";
         this.§3?§["QA"] = "QATAR";
         this.§3?§["RE"] = "RÉUNION";
         this.§3?§["RO"] = "ROMANIA";
         this.§3?§["RU"] = "RUSSIAN FEDERATION";
         this.§3?§["RW"] = "RWANDA";
         this.§3?§["BL"] = "SAINT BARTHÉLEMY";
         this.§3?§["SH"] = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA";
         this.§3?§["KN"] = "SAINT KITTS AND NEVIS";
         this.§3?§["LC"] = "SAINT LUCIA";
         this.§3?§["MF"] = "SAINT MARTIN (FRENCH PART)";
         this.§3?§["PM"] = "SAINT PIERRE AND MIQUELON";
         this.§3?§["VC"] = "SAINT VINCENT AND THE GRENADINES";
         this.§3?§["WS"] = "SAMOA";
         this.§3?§["SM"] = "SAN MARINO";
         this.§3?§["ST"] = "SAO TOME AND PRINCIPE";
         this.§3?§["SA"] = "SAUDI ARABIA";
         this.§3?§["SN"] = "SENEGAL";
         this.§3?§["RS"] = "SERBIA";
         this.§3?§["SC"] = "SEYCHELLES";
         this.§3?§["SL"] = "SIERRA LEONE";
         this.§3?§["SG"] = "SINGAPORE";
         this.§3?§["SX"] = "SINT MAARTEN (DUTCH PART)";
         this.§3?§["SK"] = "SLOVAKIA";
         this.§3?§["SI"] = "SLOVENIA";
         this.§3?§["SB"] = "SOLOMON ISLANDS";
         this.§3?§["SO"] = "SOMALIA";
         this.§3?§["ZA"] = "SOUTH AFRICA";
         this.§3?§["GS"] = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS";
         this.§3?§["SS"] = "SOUTH SUDAN";
         this.§3?§["ES"] = "SPAIN";
         this.§3?§["LK"] = "SRI LANKA";
         this.§3?§["SD"] = "SUDAN";
         this.§3?§["SR"] = "SURINAME";
         this.§3?§["SJ"] = "SVALBARD AND JAN MAYEN";
         this.§3?§["SZ"] = "SWAZILAND";
         this.§3?§["SE"] = "SWEDEN";
         this.§3?§["CH"] = "SWITZERLAND";
         this.§3?§["SY"] = "SYRIAN ARAB REPUBLIC";
         this.§3?§["TW"] = "TAIWAN, PROVINCE OF CHINA";
         this.§3?§["TJ"] = "TAJIKISTAN";
         this.§3?§["TZ"] = "TANZANIA, UNITED REPUBLIC OF";
         this.§3?§["TH"] = "THAILAND";
         this.§3?§["TL"] = "TIMOR-LESTE";
         this.§3?§["TG"] = "TOGO";
         this.§3?§["TK"] = "TOKELAU";
         this.§3?§["TO"] = "TONGA";
         this.§3?§["TT"] = "TRINIDAD AND TOBAGO";
         this.§3?§["TN"] = "TUNISIA";
         this.§3?§["TR"] = "TURKEY";
         this.§3?§["TM"] = "TURKMENISTAN";
         this.§3?§["TC"] = "TURKS AND CAICOS ISLANDS";
         this.§3?§["TV"] = "TUVALU";
         this.§3?§["UG"] = "UGANDA";
         this.§3?§["UA"] = "UKRAINE";
         this.§3?§["AE"] = "UNITED ARAB EMIRATES";
         this.§3?§["GB"] = "UNITED KINGDOM";
         this.§3?§["US"] = "UNITED STATES";
         this.§3?§["UM"] = "UNITED STATES MINOR OUTLYING ISLANDS";
         this.§3?§["UY"] = "URUGUAY";
         this.§3?§["UZ"] = "UZBEKISTAN";
         this.§3?§["VU"] = "VANUATU";
         this.§3?§["VE"] = "VENEZUELA, BOLIVARIAN REPUBLIC OF";
         this.§3?§["VN"] = "VIET NAM";
         this.§3?§["VG"] = "VIRGIN ISLANDS, BRITISH";
         this.§3?§["VI"] = "VIRGIN ISLANDS, U.S.";
         this.§3?§["WF"] = "WALLIS AND FUTUNA";
         this.§3?§["EH"] = "WESTERN SAHARA";
         this.§3?§["YE"] = "YEMEN";
         this.§3?§["ZM"] = "ZAMBIA";
         this.§3?§["ZW"] = "ZIMBABWE";
      }
      
      public static function § "D§() : §4"7§
      {
         if(§-#=§ == null)
         {
            §-#=§ = new §4"7§();
         }
         return §-#=§;
      }
      
      public function §7#b§(param1:String) : String
      {
         return this.§3?§[param1];
      }
   }
}
