package §&!_§
{
   import flash.utils.Dictionary;
   
   public class §;c§
   {
      
      private static var §"!R§:§;c§;
       
      
      private var §2#"§:Dictionary;
      
      public function §;c§()
      {
         this.§2#"§ = new Dictionary();
         super();
         this.§2#"§["AF"] = "AFGHANISTAN";
         this.§2#"§["AX"] = "ÅLAND ISLANDS";
         this.§2#"§["AL"] = "ALBANIA";
         this.§2#"§["DZ"] = "ALGERIA";
         this.§2#"§["AS"] = "AMERICAN SAMOA";
         this.§2#"§["AD"] = "ANDORRA";
         this.§2#"§["AO"] = "ANGOLA";
         this.§2#"§["AI"] = "ANGUILLA";
         this.§2#"§["AQ"] = "ANTARCTICA";
         this.§2#"§["AG"] = "ANTIGUA AND BARBUDA";
         this.§2#"§["AR"] = "ARGENTINA";
         this.§2#"§["AM"] = "ARMENIA";
         this.§2#"§["AW"] = "ARUBA";
         this.§2#"§["AU"] = "AUSTRALIA";
         this.§2#"§["AT"] = "AUSTRIA";
         this.§2#"§["AZ"] = "AZERBAIJAN";
         this.§2#"§["BS"] = "BAHAMAS";
         this.§2#"§["BH"] = "BAHRAIN";
         this.§2#"§["BD"] = "BANGLADESH";
         this.§2#"§["BB"] = "BARBADOS";
         this.§2#"§["BY"] = "BELARUS";
         this.§2#"§["BE"] = "BELGIUM";
         this.§2#"§["BZ"] = "BELIZE";
         this.§2#"§["BJ"] = "BENIN";
         this.§2#"§["BM"] = "BERMUDA";
         this.§2#"§["BT"] = "BHUTAN";
         this.§2#"§["BO"] = "BOLIVIA, PLURINATIONAL STATE OF";
         this.§2#"§["BQ"] = "BONAIRE, SINT EUSTATIUS AND SABA";
         this.§2#"§["BA"] = "BOSNIA AND HERZEGOVINA";
         this.§2#"§["BW"] = "BOTSWANA";
         this.§2#"§["BV"] = "BOUVET ISLAND";
         this.§2#"§["BR"] = "BRAZIL";
         this.§2#"§["IO"] = "BRITISH INDIAN OCEAN TERRITORY";
         this.§2#"§["BN"] = "BRUNEI DARUSSALAM";
         this.§2#"§["BG"] = "BULGARIA";
         this.§2#"§["BF"] = "BURKINA FASO";
         this.§2#"§["BI"] = "BURUNDI";
         this.§2#"§["KH"] = "CAMBODIA";
         this.§2#"§["CM"] = "CAMEROON";
         this.§2#"§["CA"] = "CANADA";
         this.§2#"§["CV"] = "CAPE VERDE";
         this.§2#"§["KY"] = "CAYMAN ISLANDS";
         this.§2#"§["CF"] = "CENTRAL AFRICAN REPUBLIC";
         this.§2#"§["TD"] = "CHAD";
         this.§2#"§["CL"] = "CHILE";
         this.§2#"§["CN"] = "CHINA";
         this.§2#"§["CX"] = "CHRISTMAS ISLAND";
         this.§2#"§["CC"] = "COCOS (KEELING) ISLANDS";
         this.§2#"§["CO"] = "COLOMBIA";
         this.§2#"§["KM"] = "COMOROS";
         this.§2#"§["CG"] = "CONGO";
         this.§2#"§["CD"] = "CONGO, THE DEMOCRATIC REPUBLIC OF THE";
         this.§2#"§["CK"] = "COOK ISLANDS";
         this.§2#"§["CR"] = "COSTA RICA";
         this.§2#"§["CI"] = "CÔTE D\'IVOIRE";
         this.§2#"§["HR"] = "CROATIA";
         this.§2#"§["CU"] = "CUBA";
         this.§2#"§["CW"] = "CURAÇAO";
         this.§2#"§["CY"] = "CYPRUS";
         this.§2#"§["CZ"] = "CZECH REPUBLIC";
         this.§2#"§["DK"] = "DENMARK";
         this.§2#"§["DJ"] = "DJIBOUTI";
         this.§2#"§["DM"] = "DOMINICA";
         this.§2#"§["DO"] = "DOMINICAN REPUBLIC";
         this.§2#"§["EC"] = "ECUADOR";
         this.§2#"§["EG"] = "EGYPT";
         this.§2#"§["SV"] = "EL SALVADOR";
         this.§2#"§["GQ"] = "EQUATORIAL GUINEA";
         this.§2#"§["ER"] = "ERITREA";
         this.§2#"§["EE"] = "ESTONIA";
         this.§2#"§["ET"] = "ETHIOPIA";
         this.§2#"§["FK"] = "FALKLAND ISLANDS (MALVINAS)";
         this.§2#"§["FO"] = "FAROE ISLANDS";
         this.§2#"§["FJ"] = "FIJI";
         this.§2#"§["FI"] = "FINLAND";
         this.§2#"§["FR"] = "FRANCE";
         this.§2#"§["GF"] = "FRENCH GUIANA";
         this.§2#"§["PF"] = "FRENCH POLYNESIA";
         this.§2#"§["TF"] = "FRENCH SOUTHERN TERRITORIES";
         this.§2#"§["GA"] = "GABON";
         this.§2#"§["GM"] = "GAMBIA";
         this.§2#"§["GE"] = "GEORGIA";
         this.§2#"§["DE"] = "GERMANY";
         this.§2#"§["GH"] = "GHANA";
         this.§2#"§["GI"] = "GIBRALTAR";
         this.§2#"§["GR"] = "GREECE";
         this.§2#"§["GL"] = "GREENLAND";
         this.§2#"§["GD"] = "GRENADA";
         this.§2#"§["GP"] = "GUADELOUPE";
         this.§2#"§["GU"] = "GUAM";
         this.§2#"§["GT"] = "GUATEMALA";
         this.§2#"§["GG"] = "GUERNSEY";
         this.§2#"§["GN"] = "GUINEA";
         this.§2#"§["GW"] = "GUINEA-BISSAU";
         this.§2#"§["GY"] = "GUYANA";
         this.§2#"§["HT"] = "HAITI";
         this.§2#"§["HM"] = "HEARD ISLAND AND MCDONALD ISLANDS";
         this.§2#"§["VA"] = "HOLY SEE (VATICAN CITY STATE)";
         this.§2#"§["HN"] = "HONDURAS";
         this.§2#"§["HK"] = "HONG KONG";
         this.§2#"§["HU"] = "HUNGARY";
         this.§2#"§["IS"] = "ICELAND";
         this.§2#"§["IN"] = "INDIA";
         this.§2#"§["ID"] = "INDONESIA";
         this.§2#"§["IR"] = "IRAN, ISLAMIC REPUBLIC OF";
         this.§2#"§["IQ"] = "IRAQ";
         this.§2#"§["IE"] = "IRELAND";
         this.§2#"§["IM"] = "ISLE OF MAN";
         this.§2#"§["IL"] = "ISRAEL";
         this.§2#"§["IT"] = "ITALY";
         this.§2#"§["JM"] = "JAMAICA";
         this.§2#"§["JP"] = "JAPAN";
         this.§2#"§["JE"] = "JERSEY";
         this.§2#"§["JO"] = "JORDAN";
         this.§2#"§["KZ"] = "KAZAKHSTAN";
         this.§2#"§["KE"] = "KENYA";
         this.§2#"§["KI"] = "KIRIBATI";
         this.§2#"§["KP"] = "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF";
         this.§2#"§["KR"] = "KOREA, REPUBLIC OF";
         this.§2#"§["KW"] = "KUWAIT";
         this.§2#"§["KG"] = "KYRGYZSTAN";
         this.§2#"§["LA"] = "LAO PEOPLE\'S DEMOCRATIC REPUBLIC";
         this.§2#"§["LV"] = "LATVIA";
         this.§2#"§["LB"] = "LEBANON";
         this.§2#"§["LS"] = "LESOTHO";
         this.§2#"§["LR"] = "LIBERIA";
         this.§2#"§["LY"] = "LIBYA";
         this.§2#"§["LI"] = "LIECHTENSTEIN";
         this.§2#"§["LT"] = "LITHUANIA";
         this.§2#"§["LU"] = "LUXEMBOURG";
         this.§2#"§["MO"] = "MACAO";
         this.§2#"§["MK"] = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF";
         this.§2#"§["MG"] = "MADAGASCAR";
         this.§2#"§["MW"] = "MALAWI";
         this.§2#"§["MY"] = "MALAYSIA";
         this.§2#"§["MV"] = "MALDIVES";
         this.§2#"§["ML"] = "MALI";
         this.§2#"§["MT"] = "MALTA";
         this.§2#"§["MH"] = "MARSHALL ISLANDS";
         this.§2#"§["MQ"] = "MARTINIQUE";
         this.§2#"§["MR"] = "MAURITANIA";
         this.§2#"§["MU"] = "MAURITIUS";
         this.§2#"§["YT"] = "MAYOTTE";
         this.§2#"§["MX"] = "MEXICO";
         this.§2#"§["FM"] = "MICRONESIA, FEDERATED STATES OF";
         this.§2#"§["MD"] = "MOLDOVA, REPUBLIC OF";
         this.§2#"§["MC"] = "MONACO";
         this.§2#"§["MN"] = "MONGOLIA";
         this.§2#"§["ME"] = "MONTENEGRO";
         this.§2#"§["MS"] = "MONTSERRAT";
         this.§2#"§["MA"] = "MOROCCO";
         this.§2#"§["MZ"] = "MOZAMBIQUE";
         this.§2#"§["MM"] = "MYANMAR";
         this.§2#"§["NA"] = "NAMIBIA";
         this.§2#"§["NR"] = "NAURU";
         this.§2#"§["NP"] = "NEPAL";
         this.§2#"§["NL"] = "NETHERLANDS";
         this.§2#"§["NC"] = "NEW CALEDONIA";
         this.§2#"§["NZ"] = "NEW ZEALAND";
         this.§2#"§["NI"] = "NICARAGUA";
         this.§2#"§["NE"] = "NIGER";
         this.§2#"§["NG"] = "NIGERIA";
         this.§2#"§["NU"] = "NIUE";
         this.§2#"§["NF"] = "NORFOLK ISLAND";
         this.§2#"§["MP"] = "NORTHERN MARIANA ISLANDS";
         this.§2#"§["NO"] = "NORWAY";
         this.§2#"§["OM"] = "OMAN";
         this.§2#"§["PK"] = "PAKISTAN";
         this.§2#"§["PW"] = "PALAU";
         this.§2#"§["PS"] = "PALESTINE, STATE OF";
         this.§2#"§["PA"] = "PANAMA";
         this.§2#"§["PG"] = "PAPUA NEW GUINEA";
         this.§2#"§["PY"] = "PARAGUAY";
         this.§2#"§["PE"] = "PERU";
         this.§2#"§["PH"] = "PHILIPPINES";
         this.§2#"§["PN"] = "PITCAIRN";
         this.§2#"§["PL"] = "POLAND";
         this.§2#"§["PT"] = "PORTUGAL";
         this.§2#"§["PR"] = "PUERTO RICO";
         this.§2#"§["QA"] = "QATAR";
         this.§2#"§["RE"] = "RÉUNION";
         this.§2#"§["RO"] = "ROMANIA";
         this.§2#"§["RU"] = "RUSSIAN FEDERATION";
         this.§2#"§["RW"] = "RWANDA";
         this.§2#"§["BL"] = "SAINT BARTHÉLEMY";
         this.§2#"§["SH"] = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA";
         this.§2#"§["KN"] = "SAINT KITTS AND NEVIS";
         this.§2#"§["LC"] = "SAINT LUCIA";
         this.§2#"§["MF"] = "SAINT MARTIN (FRENCH PART)";
         this.§2#"§["PM"] = "SAINT PIERRE AND MIQUELON";
         this.§2#"§["VC"] = "SAINT VINCENT AND THE GRENADINES";
         this.§2#"§["WS"] = "SAMOA";
         this.§2#"§["SM"] = "SAN MARINO";
         this.§2#"§["ST"] = "SAO TOME AND PRINCIPE";
         this.§2#"§["SA"] = "SAUDI ARABIA";
         this.§2#"§["SN"] = "SENEGAL";
         this.§2#"§["RS"] = "SERBIA";
         this.§2#"§["SC"] = "SEYCHELLES";
         this.§2#"§["SL"] = "SIERRA LEONE";
         this.§2#"§["SG"] = "SINGAPORE";
         this.§2#"§["SX"] = "SINT MAARTEN (DUTCH PART)";
         this.§2#"§["SK"] = "SLOVAKIA";
         this.§2#"§["SI"] = "SLOVENIA";
         this.§2#"§["SB"] = "SOLOMON ISLANDS";
         this.§2#"§["SO"] = "SOMALIA";
         this.§2#"§["ZA"] = "SOUTH AFRICA";
         this.§2#"§["GS"] = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS";
         this.§2#"§["SS"] = "SOUTH SUDAN";
         this.§2#"§["ES"] = "SPAIN";
         this.§2#"§["LK"] = "SRI LANKA";
         this.§2#"§["SD"] = "SUDAN";
         this.§2#"§["SR"] = "SURINAME";
         this.§2#"§["SJ"] = "SVALBARD AND JAN MAYEN";
         this.§2#"§["SZ"] = "SWAZILAND";
         this.§2#"§["SE"] = "SWEDEN";
         this.§2#"§["CH"] = "SWITZERLAND";
         this.§2#"§["SY"] = "SYRIAN ARAB REPUBLIC";
         this.§2#"§["TW"] = "TAIWAN, PROVINCE OF CHINA";
         this.§2#"§["TJ"] = "TAJIKISTAN";
         this.§2#"§["TZ"] = "TANZANIA, UNITED REPUBLIC OF";
         this.§2#"§["TH"] = "THAILAND";
         this.§2#"§["TL"] = "TIMOR-LESTE";
         this.§2#"§["TG"] = "TOGO";
         this.§2#"§["TK"] = "TOKELAU";
         this.§2#"§["TO"] = "TONGA";
         this.§2#"§["TT"] = "TRINIDAD AND TOBAGO";
         this.§2#"§["TN"] = "TUNISIA";
         this.§2#"§["TR"] = "TURKEY";
         this.§2#"§["TM"] = "TURKMENISTAN";
         this.§2#"§["TC"] = "TURKS AND CAICOS ISLANDS";
         this.§2#"§["TV"] = "TUVALU";
         this.§2#"§["UG"] = "UGANDA";
         this.§2#"§["UA"] = "UKRAINE";
         this.§2#"§["AE"] = "UNITED ARAB EMIRATES";
         this.§2#"§["GB"] = "UNITED KINGDOM";
         this.§2#"§["US"] = "UNITED STATES";
         this.§2#"§["UM"] = "UNITED STATES MINOR OUTLYING ISLANDS";
         this.§2#"§["UY"] = "URUGUAY";
         this.§2#"§["UZ"] = "UZBEKISTAN";
         this.§2#"§["VU"] = "VANUATU";
         this.§2#"§["VE"] = "VENEZUELA, BOLIVARIAN REPUBLIC OF";
         this.§2#"§["VN"] = "VIET NAM";
         this.§2#"§["VG"] = "VIRGIN ISLANDS, BRITISH";
         this.§2#"§["VI"] = "VIRGIN ISLANDS, U.S.";
         this.§2#"§["WF"] = "WALLIS AND FUTUNA";
         this.§2#"§["EH"] = "WESTERN SAHARA";
         this.§2#"§["YE"] = "YEMEN";
         this.§2#"§["ZM"] = "ZAMBIA";
         this.§2#"§["ZW"] = "ZIMBABWE";
      }
      
      public static function §`"H§() : §;c§
      {
         if(§"!R§ == null)
         {
            §"!R§ = new §;c§();
         }
         return §"!R§;
      }
      
      public function §+9§(param1:String) : String
      {
         return this.§2#"§[param1];
      }
   }
}
