package §2E§
{
   import flash.utils.Dictionary;
   
   public class §+"Q§
   {
      
      private static var §0!5§:§+"Q§;
       
      
      private var §4"b§:Dictionary;
      
      public function §+"Q§()
      {
         this.§4"b§ = new Dictionary();
         super();
         this.§4"b§["AF"] = "AFGHANISTAN";
         this.§4"b§["AX"] = "ÅLAND ISLANDS";
         this.§4"b§["AL"] = "ALBANIA";
         this.§4"b§["DZ"] = "ALGERIA";
         this.§4"b§["AS"] = "AMERICAN SAMOA";
         this.§4"b§["AD"] = "ANDORRA";
         this.§4"b§["AO"] = "ANGOLA";
         this.§4"b§["AI"] = "ANGUILLA";
         this.§4"b§["AQ"] = "ANTARCTICA";
         this.§4"b§["AG"] = "ANTIGUA AND BARBUDA";
         this.§4"b§["AR"] = "ARGENTINA";
         this.§4"b§["AM"] = "ARMENIA";
         this.§4"b§["AW"] = "ARUBA";
         this.§4"b§["AU"] = "AUSTRALIA";
         this.§4"b§["AT"] = "AUSTRIA";
         this.§4"b§["AZ"] = "AZERBAIJAN";
         this.§4"b§["BS"] = "BAHAMAS";
         this.§4"b§["BH"] = "BAHRAIN";
         this.§4"b§["BD"] = "BANGLADESH";
         this.§4"b§["BB"] = "BARBADOS";
         this.§4"b§["BY"] = "BELARUS";
         this.§4"b§["BE"] = "BELGIUM";
         this.§4"b§["BZ"] = "BELIZE";
         this.§4"b§["BJ"] = "BENIN";
         this.§4"b§["BM"] = "BERMUDA";
         this.§4"b§["BT"] = "BHUTAN";
         this.§4"b§["BO"] = "BOLIVIA, PLURINATIONAL STATE OF";
         this.§4"b§["BQ"] = "BONAIRE, SINT EUSTATIUS AND SABA";
         this.§4"b§["BA"] = "BOSNIA AND HERZEGOVINA";
         this.§4"b§["BW"] = "BOTSWANA";
         this.§4"b§["BV"] = "BOUVET ISLAND";
         this.§4"b§["BR"] = "BRAZIL";
         this.§4"b§["IO"] = "BRITISH INDIAN OCEAN TERRITORY";
         this.§4"b§["BN"] = "BRUNEI DARUSSALAM";
         this.§4"b§["BG"] = "BULGARIA";
         this.§4"b§["BF"] = "BURKINA FASO";
         this.§4"b§["BI"] = "BURUNDI";
         this.§4"b§["KH"] = "CAMBODIA";
         this.§4"b§["CM"] = "CAMEROON";
         this.§4"b§["CA"] = "CANADA";
         this.§4"b§["CV"] = "CAPE VERDE";
         this.§4"b§["KY"] = "CAYMAN ISLANDS";
         this.§4"b§["CF"] = "CENTRAL AFRICAN REPUBLIC";
         this.§4"b§["TD"] = "CHAD";
         this.§4"b§["CL"] = "CHILE";
         this.§4"b§["CN"] = "CHINA";
         this.§4"b§["CX"] = "CHRISTMAS ISLAND";
         this.§4"b§["CC"] = "COCOS (KEELING) ISLANDS";
         this.§4"b§["CO"] = "COLOMBIA";
         this.§4"b§["KM"] = "COMOROS";
         this.§4"b§["CG"] = "CONGO";
         this.§4"b§["CD"] = "CONGO, THE DEMOCRATIC REPUBLIC OF THE";
         this.§4"b§["CK"] = "COOK ISLANDS";
         this.§4"b§["CR"] = "COSTA RICA";
         this.§4"b§["CI"] = "CÔTE D\'IVOIRE";
         this.§4"b§["HR"] = "CROATIA";
         this.§4"b§["CU"] = "CUBA";
         this.§4"b§["CW"] = "CURAÇAO";
         this.§4"b§["CY"] = "CYPRUS";
         this.§4"b§["CZ"] = "CZECH REPUBLIC";
         this.§4"b§["DK"] = "DENMARK";
         this.§4"b§["DJ"] = "DJIBOUTI";
         this.§4"b§["DM"] = "DOMINICA";
         this.§4"b§["DO"] = "DOMINICAN REPUBLIC";
         this.§4"b§["EC"] = "ECUADOR";
         this.§4"b§["EG"] = "EGYPT";
         this.§4"b§["SV"] = "EL SALVADOR";
         this.§4"b§["GQ"] = "EQUATORIAL GUINEA";
         this.§4"b§["ER"] = "ERITREA";
         this.§4"b§["EE"] = "ESTONIA";
         this.§4"b§["ET"] = "ETHIOPIA";
         this.§4"b§["FK"] = "FALKLAND ISLANDS (MALVINAS)";
         this.§4"b§["FO"] = "FAROE ISLANDS";
         this.§4"b§["FJ"] = "FIJI";
         this.§4"b§["FI"] = "FINLAND";
         this.§4"b§["FR"] = "FRANCE";
         this.§4"b§["GF"] = "FRENCH GUIANA";
         this.§4"b§["PF"] = "FRENCH POLYNESIA";
         this.§4"b§["TF"] = "FRENCH SOUTHERN TERRITORIES";
         this.§4"b§["GA"] = "GABON";
         this.§4"b§["GM"] = "GAMBIA";
         this.§4"b§["GE"] = "GEORGIA";
         this.§4"b§["DE"] = "GERMANY";
         this.§4"b§["GH"] = "GHANA";
         this.§4"b§["GI"] = "GIBRALTAR";
         this.§4"b§["GR"] = "GREECE";
         this.§4"b§["GL"] = "GREENLAND";
         this.§4"b§["GD"] = "GRENADA";
         this.§4"b§["GP"] = "GUADELOUPE";
         this.§4"b§["GU"] = "GUAM";
         this.§4"b§["GT"] = "GUATEMALA";
         this.§4"b§["GG"] = "GUERNSEY";
         this.§4"b§["GN"] = "GUINEA";
         this.§4"b§["GW"] = "GUINEA-BISSAU";
         this.§4"b§["GY"] = "GUYANA";
         this.§4"b§["HT"] = "HAITI";
         this.§4"b§["HM"] = "HEARD ISLAND AND MCDONALD ISLANDS";
         this.§4"b§["VA"] = "HOLY SEE (VATICAN CITY STATE)";
         this.§4"b§["HN"] = "HONDURAS";
         this.§4"b§["HK"] = "HONG KONG";
         this.§4"b§["HU"] = "HUNGARY";
         this.§4"b§["IS"] = "ICELAND";
         this.§4"b§["IN"] = "INDIA";
         this.§4"b§["ID"] = "INDONESIA";
         this.§4"b§["IR"] = "IRAN, ISLAMIC REPUBLIC OF";
         this.§4"b§["IQ"] = "IRAQ";
         this.§4"b§["IE"] = "IRELAND";
         this.§4"b§["IM"] = "ISLE OF MAN";
         this.§4"b§["IL"] = "ISRAEL";
         this.§4"b§["IT"] = "ITALY";
         this.§4"b§["JM"] = "JAMAICA";
         this.§4"b§["JP"] = "JAPAN";
         this.§4"b§["JE"] = "JERSEY";
         this.§4"b§["JO"] = "JORDAN";
         this.§4"b§["KZ"] = "KAZAKHSTAN";
         this.§4"b§["KE"] = "KENYA";
         this.§4"b§["KI"] = "KIRIBATI";
         this.§4"b§["KP"] = "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF";
         this.§4"b§["KR"] = "KOREA, REPUBLIC OF";
         this.§4"b§["KW"] = "KUWAIT";
         this.§4"b§["KG"] = "KYRGYZSTAN";
         this.§4"b§["LA"] = "LAO PEOPLE\'S DEMOCRATIC REPUBLIC";
         this.§4"b§["LV"] = "LATVIA";
         this.§4"b§["LB"] = "LEBANON";
         this.§4"b§["LS"] = "LESOTHO";
         this.§4"b§["LR"] = "LIBERIA";
         this.§4"b§["LY"] = "LIBYA";
         this.§4"b§["LI"] = "LIECHTENSTEIN";
         this.§4"b§["LT"] = "LITHUANIA";
         this.§4"b§["LU"] = "LUXEMBOURG";
         this.§4"b§["MO"] = "MACAO";
         this.§4"b§["MK"] = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF";
         this.§4"b§["MG"] = "MADAGASCAR";
         this.§4"b§["MW"] = "MALAWI";
         this.§4"b§["MY"] = "MALAYSIA";
         this.§4"b§["MV"] = "MALDIVES";
         this.§4"b§["ML"] = "MALI";
         this.§4"b§["MT"] = "MALTA";
         this.§4"b§["MH"] = "MARSHALL ISLANDS";
         this.§4"b§["MQ"] = "MARTINIQUE";
         this.§4"b§["MR"] = "MAURITANIA";
         this.§4"b§["MU"] = "MAURITIUS";
         this.§4"b§["YT"] = "MAYOTTE";
         this.§4"b§["MX"] = "MEXICO";
         this.§4"b§["FM"] = "MICRONESIA, FEDERATED STATES OF";
         this.§4"b§["MD"] = "MOLDOVA, REPUBLIC OF";
         this.§4"b§["MC"] = "MONACO";
         this.§4"b§["MN"] = "MONGOLIA";
         this.§4"b§["ME"] = "MONTENEGRO";
         this.§4"b§["MS"] = "MONTSERRAT";
         this.§4"b§["MA"] = "MOROCCO";
         this.§4"b§["MZ"] = "MOZAMBIQUE";
         this.§4"b§["MM"] = "MYANMAR";
         this.§4"b§["NA"] = "NAMIBIA";
         this.§4"b§["NR"] = "NAURU";
         this.§4"b§["NP"] = "NEPAL";
         this.§4"b§["NL"] = "NETHERLANDS";
         this.§4"b§["NC"] = "NEW CALEDONIA";
         this.§4"b§["NZ"] = "NEW ZEALAND";
         this.§4"b§["NI"] = "NICARAGUA";
         this.§4"b§["NE"] = "NIGER";
         this.§4"b§["NG"] = "NIGERIA";
         this.§4"b§["NU"] = "NIUE";
         this.§4"b§["NF"] = "NORFOLK ISLAND";
         this.§4"b§["MP"] = "NORTHERN MARIANA ISLANDS";
         this.§4"b§["NO"] = "NORWAY";
         this.§4"b§["OM"] = "OMAN";
         this.§4"b§["PK"] = "PAKISTAN";
         this.§4"b§["PW"] = "PALAU";
         this.§4"b§["PS"] = "PALESTINE, STATE OF";
         this.§4"b§["PA"] = "PANAMA";
         this.§4"b§["PG"] = "PAPUA NEW GUINEA";
         this.§4"b§["PY"] = "PARAGUAY";
         this.§4"b§["PE"] = "PERU";
         this.§4"b§["PH"] = "PHILIPPINES";
         this.§4"b§["PN"] = "PITCAIRN";
         this.§4"b§["PL"] = "POLAND";
         this.§4"b§["PT"] = "PORTUGAL";
         this.§4"b§["PR"] = "PUERTO RICO";
         this.§4"b§["QA"] = "QATAR";
         this.§4"b§["RE"] = "RÉUNION";
         this.§4"b§["RO"] = "ROMANIA";
         this.§4"b§["RU"] = "RUSSIAN FEDERATION";
         this.§4"b§["RW"] = "RWANDA";
         this.§4"b§["BL"] = "SAINT BARTHÉLEMY";
         this.§4"b§["SH"] = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA";
         this.§4"b§["KN"] = "SAINT KITTS AND NEVIS";
         this.§4"b§["LC"] = "SAINT LUCIA";
         this.§4"b§["MF"] = "SAINT MARTIN (FRENCH PART)";
         this.§4"b§["PM"] = "SAINT PIERRE AND MIQUELON";
         this.§4"b§["VC"] = "SAINT VINCENT AND THE GRENADINES";
         this.§4"b§["WS"] = "SAMOA";
         this.§4"b§["SM"] = "SAN MARINO";
         this.§4"b§["ST"] = "SAO TOME AND PRINCIPE";
         this.§4"b§["SA"] = "SAUDI ARABIA";
         this.§4"b§["SN"] = "SENEGAL";
         this.§4"b§["RS"] = "SERBIA";
         this.§4"b§["SC"] = "SEYCHELLES";
         this.§4"b§["SL"] = "SIERRA LEONE";
         this.§4"b§["SG"] = "SINGAPORE";
         this.§4"b§["SX"] = "SINT MAARTEN (DUTCH PART)";
         this.§4"b§["SK"] = "SLOVAKIA";
         this.§4"b§["SI"] = "SLOVENIA";
         this.§4"b§["SB"] = "SOLOMON ISLANDS";
         this.§4"b§["SO"] = "SOMALIA";
         this.§4"b§["ZA"] = "SOUTH AFRICA";
         this.§4"b§["GS"] = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS";
         this.§4"b§["SS"] = "SOUTH SUDAN";
         this.§4"b§["ES"] = "SPAIN";
         this.§4"b§["LK"] = "SRI LANKA";
         this.§4"b§["SD"] = "SUDAN";
         this.§4"b§["SR"] = "SURINAME";
         this.§4"b§["SJ"] = "SVALBARD AND JAN MAYEN";
         this.§4"b§["SZ"] = "SWAZILAND";
         this.§4"b§["SE"] = "SWEDEN";
         this.§4"b§["CH"] = "SWITZERLAND";
         this.§4"b§["SY"] = "SYRIAN ARAB REPUBLIC";
         this.§4"b§["TW"] = "TAIWAN, PROVINCE OF CHINA";
         this.§4"b§["TJ"] = "TAJIKISTAN";
         this.§4"b§["TZ"] = "TANZANIA, UNITED REPUBLIC OF";
         this.§4"b§["TH"] = "THAILAND";
         this.§4"b§["TL"] = "TIMOR-LESTE";
         this.§4"b§["TG"] = "TOGO";
         this.§4"b§["TK"] = "TOKELAU";
         this.§4"b§["TO"] = "TONGA";
         this.§4"b§["TT"] = "TRINIDAD AND TOBAGO";
         this.§4"b§["TN"] = "TUNISIA";
         this.§4"b§["TR"] = "TURKEY";
         this.§4"b§["TM"] = "TURKMENISTAN";
         this.§4"b§["TC"] = "TURKS AND CAICOS ISLANDS";
         this.§4"b§["TV"] = "TUVALU";
         this.§4"b§["UG"] = "UGANDA";
         this.§4"b§["UA"] = "UKRAINE";
         this.§4"b§["AE"] = "UNITED ARAB EMIRATES";
         this.§4"b§["GB"] = "UNITED KINGDOM";
         this.§4"b§["US"] = "UNITED STATES";
         this.§4"b§["UM"] = "UNITED STATES MINOR OUTLYING ISLANDS";
         this.§4"b§["UY"] = "URUGUAY";
         this.§4"b§["UZ"] = "UZBEKISTAN";
         this.§4"b§["VU"] = "VANUATU";
         this.§4"b§["VE"] = "VENEZUELA, BOLIVARIAN REPUBLIC OF";
         this.§4"b§["VN"] = "VIET NAM";
         this.§4"b§["VG"] = "VIRGIN ISLANDS, BRITISH";
         this.§4"b§["VI"] = "VIRGIN ISLANDS, U.S.";
         this.§4"b§["WF"] = "WALLIS AND FUTUNA";
         this.§4"b§["EH"] = "WESTERN SAHARA";
         this.§4"b§["YE"] = "YEMEN";
         this.§4"b§["ZM"] = "ZAMBIA";
         this.§4"b§["ZW"] = "ZIMBABWE";
      }
      
      public static function §3"1§() : §+"Q§
      {
         if(§0!5§ == null)
         {
            §0!5§ = new §+"Q§();
         }
         return §0!5§;
      }
      
      public function §!O§(param1:String) : String
      {
         return this.§4"b§[param1];
      }
   }
}
