package §+#B§
{
   import flash.utils.Dictionary;
   
   public class §2$6§
   {
      
      private static var §7"A§:§2$6§;
       
      
      private var §`!a§:Dictionary;
      
      public function §2$6§()
      {
         this.§`!a§ = new Dictionary();
         super();
         this.§`!a§["AF"] = "AFGHANISTAN";
         this.§`!a§["AX"] = "ÅLAND ISLANDS";
         this.§`!a§["AL"] = "ALBANIA";
         this.§`!a§["DZ"] = "ALGERIA";
         this.§`!a§["AS"] = "AMERICAN SAMOA";
         this.§`!a§["AD"] = "ANDORRA";
         this.§`!a§["AO"] = "ANGOLA";
         this.§`!a§["AI"] = "ANGUILLA";
         this.§`!a§["AQ"] = "ANTARCTICA";
         this.§`!a§["AG"] = "ANTIGUA AND BARBUDA";
         this.§`!a§["AR"] = "ARGENTINA";
         this.§`!a§["AM"] = "ARMENIA";
         this.§`!a§["AW"] = "ARUBA";
         this.§`!a§["AU"] = "AUSTRALIA";
         this.§`!a§["AT"] = "AUSTRIA";
         this.§`!a§["AZ"] = "AZERBAIJAN";
         this.§`!a§["BS"] = "BAHAMAS";
         this.§`!a§["BH"] = "BAHRAIN";
         this.§`!a§["BD"] = "BANGLADESH";
         this.§`!a§["BB"] = "BARBADOS";
         this.§`!a§["BY"] = "BELARUS";
         this.§`!a§["BE"] = "BELGIUM";
         this.§`!a§["BZ"] = "BELIZE";
         this.§`!a§["BJ"] = "BENIN";
         this.§`!a§["BM"] = "BERMUDA";
         this.§`!a§["BT"] = "BHUTAN";
         this.§`!a§["BO"] = "BOLIVIA, PLURINATIONAL STATE OF";
         this.§`!a§["BQ"] = "BONAIRE, SINT EUSTATIUS AND SABA";
         this.§`!a§["BA"] = "BOSNIA AND HERZEGOVINA";
         this.§`!a§["BW"] = "BOTSWANA";
         this.§`!a§["BV"] = "BOUVET ISLAND";
         this.§`!a§["BR"] = "BRAZIL";
         this.§`!a§["IO"] = "BRITISH INDIAN OCEAN TERRITORY";
         this.§`!a§["BN"] = "BRUNEI DARUSSALAM";
         this.§`!a§["BG"] = "BULGARIA";
         this.§`!a§["BF"] = "BURKINA FASO";
         this.§`!a§["BI"] = "BURUNDI";
         this.§`!a§["KH"] = "CAMBODIA";
         this.§`!a§["CM"] = "CAMEROON";
         this.§`!a§["CA"] = "CANADA";
         this.§`!a§["CV"] = "CAPE VERDE";
         this.§`!a§["KY"] = "CAYMAN ISLANDS";
         this.§`!a§["CF"] = "CENTRAL AFRICAN REPUBLIC";
         this.§`!a§["TD"] = "CHAD";
         this.§`!a§["CL"] = "CHILE";
         this.§`!a§["CN"] = "CHINA";
         this.§`!a§["CX"] = "CHRISTMAS ISLAND";
         this.§`!a§["CC"] = "COCOS (KEELING) ISLANDS";
         this.§`!a§["CO"] = "COLOMBIA";
         this.§`!a§["KM"] = "COMOROS";
         this.§`!a§["CG"] = "CONGO";
         this.§`!a§["CD"] = "CONGO, THE DEMOCRATIC REPUBLIC OF THE";
         this.§`!a§["CK"] = "COOK ISLANDS";
         this.§`!a§["CR"] = "COSTA RICA";
         this.§`!a§["CI"] = "CÔTE D\'IVOIRE";
         this.§`!a§["HR"] = "CROATIA";
         this.§`!a§["CU"] = "CUBA";
         this.§`!a§["CW"] = "CURAÇAO";
         this.§`!a§["CY"] = "CYPRUS";
         this.§`!a§["CZ"] = "CZECH REPUBLIC";
         this.§`!a§["DK"] = "DENMARK";
         this.§`!a§["DJ"] = "DJIBOUTI";
         this.§`!a§["DM"] = "DOMINICA";
         this.§`!a§["DO"] = "DOMINICAN REPUBLIC";
         this.§`!a§["EC"] = "ECUADOR";
         this.§`!a§["EG"] = "EGYPT";
         this.§`!a§["SV"] = "EL SALVADOR";
         this.§`!a§["GQ"] = "EQUATORIAL GUINEA";
         this.§`!a§["ER"] = "ERITREA";
         this.§`!a§["EE"] = "ESTONIA";
         this.§`!a§["ET"] = "ETHIOPIA";
         this.§`!a§["FK"] = "FALKLAND ISLANDS (MALVINAS)";
         this.§`!a§["FO"] = "FAROE ISLANDS";
         this.§`!a§["FJ"] = "FIJI";
         this.§`!a§["FI"] = "FINLAND";
         this.§`!a§["FR"] = "FRANCE";
         this.§`!a§["GF"] = "FRENCH GUIANA";
         this.§`!a§["PF"] = "FRENCH POLYNESIA";
         this.§`!a§["TF"] = "FRENCH SOUTHERN TERRITORIES";
         this.§`!a§["GA"] = "GABON";
         this.§`!a§["GM"] = "GAMBIA";
         this.§`!a§["GE"] = "GEORGIA";
         this.§`!a§["DE"] = "GERMANY";
         this.§`!a§["GH"] = "GHANA";
         this.§`!a§["GI"] = "GIBRALTAR";
         this.§`!a§["GR"] = "GREECE";
         this.§`!a§["GL"] = "GREENLAND";
         this.§`!a§["GD"] = "GRENADA";
         this.§`!a§["GP"] = "GUADELOUPE";
         this.§`!a§["GU"] = "GUAM";
         this.§`!a§["GT"] = "GUATEMALA";
         this.§`!a§["GG"] = "GUERNSEY";
         this.§`!a§["GN"] = "GUINEA";
         this.§`!a§["GW"] = "GUINEA-BISSAU";
         this.§`!a§["GY"] = "GUYANA";
         this.§`!a§["HT"] = "HAITI";
         this.§`!a§["HM"] = "HEARD ISLAND AND MCDONALD ISLANDS";
         this.§`!a§["VA"] = "HOLY SEE (VATICAN CITY STATE)";
         this.§`!a§["HN"] = "HONDURAS";
         this.§`!a§["HK"] = "HONG KONG";
         this.§`!a§["HU"] = "HUNGARY";
         this.§`!a§["IS"] = "ICELAND";
         this.§`!a§["IN"] = "INDIA";
         this.§`!a§["ID"] = "INDONESIA";
         this.§`!a§["IR"] = "IRAN, ISLAMIC REPUBLIC OF";
         this.§`!a§["IQ"] = "IRAQ";
         this.§`!a§["IE"] = "IRELAND";
         this.§`!a§["IM"] = "ISLE OF MAN";
         this.§`!a§["IL"] = "ISRAEL";
         this.§`!a§["IT"] = "ITALY";
         this.§`!a§["JM"] = "JAMAICA";
         this.§`!a§["JP"] = "JAPAN";
         this.§`!a§["JE"] = "JERSEY";
         this.§`!a§["JO"] = "JORDAN";
         this.§`!a§["KZ"] = "KAZAKHSTAN";
         this.§`!a§["KE"] = "KENYA";
         this.§`!a§["KI"] = "KIRIBATI";
         this.§`!a§["KP"] = "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF";
         this.§`!a§["KR"] = "KOREA, REPUBLIC OF";
         this.§`!a§["KW"] = "KUWAIT";
         this.§`!a§["KG"] = "KYRGYZSTAN";
         this.§`!a§["LA"] = "LAO PEOPLE\'S DEMOCRATIC REPUBLIC";
         this.§`!a§["LV"] = "LATVIA";
         this.§`!a§["LB"] = "LEBANON";
         this.§`!a§["LS"] = "LESOTHO";
         this.§`!a§["LR"] = "LIBERIA";
         this.§`!a§["LY"] = "LIBYA";
         this.§`!a§["LI"] = "LIECHTENSTEIN";
         this.§`!a§["LT"] = "LITHUANIA";
         this.§`!a§["LU"] = "LUXEMBOURG";
         this.§`!a§["MO"] = "MACAO";
         this.§`!a§["MK"] = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF";
         this.§`!a§["MG"] = "MADAGASCAR";
         this.§`!a§["MW"] = "MALAWI";
         this.§`!a§["MY"] = "MALAYSIA";
         this.§`!a§["MV"] = "MALDIVES";
         this.§`!a§["ML"] = "MALI";
         this.§`!a§["MT"] = "MALTA";
         this.§`!a§["MH"] = "MARSHALL ISLANDS";
         this.§`!a§["MQ"] = "MARTINIQUE";
         this.§`!a§["MR"] = "MAURITANIA";
         this.§`!a§["MU"] = "MAURITIUS";
         this.§`!a§["YT"] = "MAYOTTE";
         this.§`!a§["MX"] = "MEXICO";
         this.§`!a§["FM"] = "MICRONESIA, FEDERATED STATES OF";
         this.§`!a§["MD"] = "MOLDOVA, REPUBLIC OF";
         this.§`!a§["MC"] = "MONACO";
         this.§`!a§["MN"] = "MONGOLIA";
         this.§`!a§["ME"] = "MONTENEGRO";
         this.§`!a§["MS"] = "MONTSERRAT";
         this.§`!a§["MA"] = "MOROCCO";
         this.§`!a§["MZ"] = "MOZAMBIQUE";
         this.§`!a§["MM"] = "MYANMAR";
         this.§`!a§["NA"] = "NAMIBIA";
         this.§`!a§["NR"] = "NAURU";
         this.§`!a§["NP"] = "NEPAL";
         this.§`!a§["NL"] = "NETHERLANDS";
         this.§`!a§["NC"] = "NEW CALEDONIA";
         this.§`!a§["NZ"] = "NEW ZEALAND";
         this.§`!a§["NI"] = "NICARAGUA";
         this.§`!a§["NE"] = "NIGER";
         this.§`!a§["NG"] = "NIGERIA";
         this.§`!a§["NU"] = "NIUE";
         this.§`!a§["NF"] = "NORFOLK ISLAND";
         this.§`!a§["MP"] = "NORTHERN MARIANA ISLANDS";
         this.§`!a§["NO"] = "NORWAY";
         this.§`!a§["OM"] = "OMAN";
         this.§`!a§["PK"] = "PAKISTAN";
         this.§`!a§["PW"] = "PALAU";
         this.§`!a§["PS"] = "PALESTINE, STATE OF";
         this.§`!a§["PA"] = "PANAMA";
         this.§`!a§["PG"] = "PAPUA NEW GUINEA";
         this.§`!a§["PY"] = "PARAGUAY";
         this.§`!a§["PE"] = "PERU";
         this.§`!a§["PH"] = "PHILIPPINES";
         this.§`!a§["PN"] = "PITCAIRN";
         this.§`!a§["PL"] = "POLAND";
         this.§`!a§["PT"] = "PORTUGAL";
         this.§`!a§["PR"] = "PUERTO RICO";
         this.§`!a§["QA"] = "QATAR";
         this.§`!a§["RE"] = "RÉUNION";
         this.§`!a§["RO"] = "ROMANIA";
         this.§`!a§["RU"] = "RUSSIAN FEDERATION";
         this.§`!a§["RW"] = "RWANDA";
         this.§`!a§["BL"] = "SAINT BARTHÉLEMY";
         this.§`!a§["SH"] = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA";
         this.§`!a§["KN"] = "SAINT KITTS AND NEVIS";
         this.§`!a§["LC"] = "SAINT LUCIA";
         this.§`!a§["MF"] = "SAINT MARTIN (FRENCH PART)";
         this.§`!a§["PM"] = "SAINT PIERRE AND MIQUELON";
         this.§`!a§["VC"] = "SAINT VINCENT AND THE GRENADINES";
         this.§`!a§["WS"] = "SAMOA";
         this.§`!a§["SM"] = "SAN MARINO";
         this.§`!a§["ST"] = "SAO TOME AND PRINCIPE";
         this.§`!a§["SA"] = "SAUDI ARABIA";
         this.§`!a§["SN"] = "SENEGAL";
         this.§`!a§["RS"] = "SERBIA";
         this.§`!a§["SC"] = "SEYCHELLES";
         this.§`!a§["SL"] = "SIERRA LEONE";
         this.§`!a§["SG"] = "SINGAPORE";
         this.§`!a§["SX"] = "SINT MAARTEN (DUTCH PART)";
         this.§`!a§["SK"] = "SLOVAKIA";
         this.§`!a§["SI"] = "SLOVENIA";
         this.§`!a§["SB"] = "SOLOMON ISLANDS";
         this.§`!a§["SO"] = "SOMALIA";
         this.§`!a§["ZA"] = "SOUTH AFRICA";
         this.§`!a§["GS"] = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS";
         this.§`!a§["SS"] = "SOUTH SUDAN";
         this.§`!a§["ES"] = "SPAIN";
         this.§`!a§["LK"] = "SRI LANKA";
         this.§`!a§["SD"] = "SUDAN";
         this.§`!a§["SR"] = "SURINAME";
         this.§`!a§["SJ"] = "SVALBARD AND JAN MAYEN";
         this.§`!a§["SZ"] = "SWAZILAND";
         this.§`!a§["SE"] = "SWEDEN";
         this.§`!a§["CH"] = "SWITZERLAND";
         this.§`!a§["SY"] = "SYRIAN ARAB REPUBLIC";
         this.§`!a§["TW"] = "TAIWAN, PROVINCE OF CHINA";
         this.§`!a§["TJ"] = "TAJIKISTAN";
         this.§`!a§["TZ"] = "TANZANIA, UNITED REPUBLIC OF";
         this.§`!a§["TH"] = "THAILAND";
         this.§`!a§["TL"] = "TIMOR-LESTE";
         this.§`!a§["TG"] = "TOGO";
         this.§`!a§["TK"] = "TOKELAU";
         this.§`!a§["TO"] = "TONGA";
         this.§`!a§["TT"] = "TRINIDAD AND TOBAGO";
         this.§`!a§["TN"] = "TUNISIA";
         this.§`!a§["TR"] = "TURKEY";
         this.§`!a§["TM"] = "TURKMENISTAN";
         this.§`!a§["TC"] = "TURKS AND CAICOS ISLANDS";
         this.§`!a§["TV"] = "TUVALU";
         this.§`!a§["UG"] = "UGANDA";
         this.§`!a§["UA"] = "UKRAINE";
         this.§`!a§["AE"] = "UNITED ARAB EMIRATES";
         this.§`!a§["GB"] = "UNITED KINGDOM";
         this.§`!a§["US"] = "UNITED STATES";
         this.§`!a§["UM"] = "UNITED STATES MINOR OUTLYING ISLANDS";
         this.§`!a§["UY"] = "URUGUAY";
         this.§`!a§["UZ"] = "UZBEKISTAN";
         this.§`!a§["VU"] = "VANUATU";
         this.§`!a§["VE"] = "VENEZUELA, BOLIVARIAN REPUBLIC OF";
         this.§`!a§["VN"] = "VIET NAM";
         this.§`!a§["VG"] = "VIRGIN ISLANDS, BRITISH";
         this.§`!a§["VI"] = "VIRGIN ISLANDS, U.S.";
         this.§`!a§["WF"] = "WALLIS AND FUTUNA";
         this.§`!a§["EH"] = "WESTERN SAHARA";
         this.§`!a§["YE"] = "YEMEN";
         this.§`!a§["ZM"] = "ZAMBIA";
         this.§`!a§["ZW"] = "ZIMBABWE";
      }
      
      public static function §?q§() : §2$6§
      {
         if(§7"A§ == null)
         {
            §7"A§ = new §2$6§();
         }
         return §7"A§;
      }
      
      public function §0!F§(param1:String) : String
      {
         return this.§`!a§[param1];
      }
   }
}
