package §>!#§
{
   import flash.utils.Dictionary;
   
   public class §8J§
   {
      
      private static var §2!Q§:§8J§;
       
      
      private var §^"?§:Dictionary;
      
      public function §8J§()
      {
         this.§^"?§ = new Dictionary();
         super();
         this.§^"?§["AF"] = "AFGHANISTAN";
         this.§^"?§["AX"] = "ÅLAND ISLANDS";
         this.§^"?§["AL"] = "ALBANIA";
         this.§^"?§["DZ"] = "ALGERIA";
         this.§^"?§["AS"] = "AMERICAN SAMOA";
         this.§^"?§["AD"] = "ANDORRA";
         this.§^"?§["AO"] = "ANGOLA";
         this.§^"?§["AI"] = "ANGUILLA";
         this.§^"?§["AQ"] = "ANTARCTICA";
         this.§^"?§["AG"] = "ANTIGUA AND BARBUDA";
         this.§^"?§["AR"] = "ARGENTINA";
         this.§^"?§["AM"] = "ARMENIA";
         this.§^"?§["AW"] = "ARUBA";
         this.§^"?§["AU"] = "AUSTRALIA";
         this.§^"?§["AT"] = "AUSTRIA";
         this.§^"?§["AZ"] = "AZERBAIJAN";
         this.§^"?§["BS"] = "BAHAMAS";
         this.§^"?§["BH"] = "BAHRAIN";
         this.§^"?§["BD"] = "BANGLADESH";
         this.§^"?§["BB"] = "BARBADOS";
         this.§^"?§["BY"] = "BELARUS";
         this.§^"?§["BE"] = "BELGIUM";
         this.§^"?§["BZ"] = "BELIZE";
         this.§^"?§["BJ"] = "BENIN";
         this.§^"?§["BM"] = "BERMUDA";
         this.§^"?§["BT"] = "BHUTAN";
         this.§^"?§["BO"] = "BOLIVIA, PLURINATIONAL STATE OF";
         this.§^"?§["BQ"] = "BONAIRE, SINT EUSTATIUS AND SABA";
         this.§^"?§["BA"] = "BOSNIA AND HERZEGOVINA";
         this.§^"?§["BW"] = "BOTSWANA";
         this.§^"?§["BV"] = "BOUVET ISLAND";
         this.§^"?§["BR"] = "BRAZIL";
         this.§^"?§["IO"] = "BRITISH INDIAN OCEAN TERRITORY";
         this.§^"?§["BN"] = "BRUNEI DARUSSALAM";
         this.§^"?§["BG"] = "BULGARIA";
         this.§^"?§["BF"] = "BURKINA FASO";
         this.§^"?§["BI"] = "BURUNDI";
         this.§^"?§["KH"] = "CAMBODIA";
         this.§^"?§["CM"] = "CAMEROON";
         this.§^"?§["CA"] = "CANADA";
         this.§^"?§["CV"] = "CAPE VERDE";
         this.§^"?§["KY"] = "CAYMAN ISLANDS";
         this.§^"?§["CF"] = "CENTRAL AFRICAN REPUBLIC";
         this.§^"?§["TD"] = "CHAD";
         this.§^"?§["CL"] = "CHILE";
         this.§^"?§["CN"] = "CHINA";
         this.§^"?§["CX"] = "CHRISTMAS ISLAND";
         this.§^"?§["CC"] = "COCOS (KEELING) ISLANDS";
         this.§^"?§["CO"] = "COLOMBIA";
         this.§^"?§["KM"] = "COMOROS";
         this.§^"?§["CG"] = "CONGO";
         this.§^"?§["CD"] = "CONGO, THE DEMOCRATIC REPUBLIC OF THE";
         this.§^"?§["CK"] = "COOK ISLANDS";
         this.§^"?§["CR"] = "COSTA RICA";
         this.§^"?§["CI"] = "CÔTE D\'IVOIRE";
         this.§^"?§["HR"] = "CROATIA";
         this.§^"?§["CU"] = "CUBA";
         this.§^"?§["CW"] = "CURAÇAO";
         this.§^"?§["CY"] = "CYPRUS";
         this.§^"?§["CZ"] = "CZECH REPUBLIC";
         this.§^"?§["DK"] = "DENMARK";
         this.§^"?§["DJ"] = "DJIBOUTI";
         this.§^"?§["DM"] = "DOMINICA";
         this.§^"?§["DO"] = "DOMINICAN REPUBLIC";
         this.§^"?§["EC"] = "ECUADOR";
         this.§^"?§["EG"] = "EGYPT";
         this.§^"?§["SV"] = "EL SALVADOR";
         this.§^"?§["GQ"] = "EQUATORIAL GUINEA";
         this.§^"?§["ER"] = "ERITREA";
         this.§^"?§["EE"] = "ESTONIA";
         this.§^"?§["ET"] = "ETHIOPIA";
         this.§^"?§["FK"] = "FALKLAND ISLANDS (MALVINAS)";
         this.§^"?§["FO"] = "FAROE ISLANDS";
         this.§^"?§["FJ"] = "FIJI";
         this.§^"?§["FI"] = "FINLAND";
         this.§^"?§["FR"] = "FRANCE";
         this.§^"?§["GF"] = "FRENCH GUIANA";
         this.§^"?§["PF"] = "FRENCH POLYNESIA";
         this.§^"?§["TF"] = "FRENCH SOUTHERN TERRITORIES";
         this.§^"?§["GA"] = "GABON";
         this.§^"?§["GM"] = "GAMBIA";
         this.§^"?§["GE"] = "GEORGIA";
         this.§^"?§["DE"] = "GERMANY";
         this.§^"?§["GH"] = "GHANA";
         this.§^"?§["GI"] = "GIBRALTAR";
         this.§^"?§["GR"] = "GREECE";
         this.§^"?§["GL"] = "GREENLAND";
         this.§^"?§["GD"] = "GRENADA";
         this.§^"?§["GP"] = "GUADELOUPE";
         this.§^"?§["GU"] = "GUAM";
         this.§^"?§["GT"] = "GUATEMALA";
         this.§^"?§["GG"] = "GUERNSEY";
         this.§^"?§["GN"] = "GUINEA";
         this.§^"?§["GW"] = "GUINEA-BISSAU";
         this.§^"?§["GY"] = "GUYANA";
         this.§^"?§["HT"] = "HAITI";
         this.§^"?§["HM"] = "HEARD ISLAND AND MCDONALD ISLANDS";
         this.§^"?§["VA"] = "HOLY SEE (VATICAN CITY STATE)";
         this.§^"?§["HN"] = "HONDURAS";
         this.§^"?§["HK"] = "HONG KONG";
         this.§^"?§["HU"] = "HUNGARY";
         this.§^"?§["IS"] = "ICELAND";
         this.§^"?§["IN"] = "INDIA";
         this.§^"?§["ID"] = "INDONESIA";
         this.§^"?§["IR"] = "IRAN, ISLAMIC REPUBLIC OF";
         this.§^"?§["IQ"] = "IRAQ";
         this.§^"?§["IE"] = "IRELAND";
         this.§^"?§["IM"] = "ISLE OF MAN";
         this.§^"?§["IL"] = "ISRAEL";
         this.§^"?§["IT"] = "ITALY";
         this.§^"?§["JM"] = "JAMAICA";
         this.§^"?§["JP"] = "JAPAN";
         this.§^"?§["JE"] = "JERSEY";
         this.§^"?§["JO"] = "JORDAN";
         this.§^"?§["KZ"] = "KAZAKHSTAN";
         this.§^"?§["KE"] = "KENYA";
         this.§^"?§["KI"] = "KIRIBATI";
         this.§^"?§["KP"] = "KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF";
         this.§^"?§["KR"] = "KOREA, REPUBLIC OF";
         this.§^"?§["KW"] = "KUWAIT";
         this.§^"?§["KG"] = "KYRGYZSTAN";
         this.§^"?§["LA"] = "LAO PEOPLE\'S DEMOCRATIC REPUBLIC";
         this.§^"?§["LV"] = "LATVIA";
         this.§^"?§["LB"] = "LEBANON";
         this.§^"?§["LS"] = "LESOTHO";
         this.§^"?§["LR"] = "LIBERIA";
         this.§^"?§["LY"] = "LIBYA";
         this.§^"?§["LI"] = "LIECHTENSTEIN";
         this.§^"?§["LT"] = "LITHUANIA";
         this.§^"?§["LU"] = "LUXEMBOURG";
         this.§^"?§["MO"] = "MACAO";
         this.§^"?§["MK"] = "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF";
         this.§^"?§["MG"] = "MADAGASCAR";
         this.§^"?§["MW"] = "MALAWI";
         this.§^"?§["MY"] = "MALAYSIA";
         this.§^"?§["MV"] = "MALDIVES";
         this.§^"?§["ML"] = "MALI";
         this.§^"?§["MT"] = "MALTA";
         this.§^"?§["MH"] = "MARSHALL ISLANDS";
         this.§^"?§["MQ"] = "MARTINIQUE";
         this.§^"?§["MR"] = "MAURITANIA";
         this.§^"?§["MU"] = "MAURITIUS";
         this.§^"?§["YT"] = "MAYOTTE";
         this.§^"?§["MX"] = "MEXICO";
         this.§^"?§["FM"] = "MICRONESIA, FEDERATED STATES OF";
         this.§^"?§["MD"] = "MOLDOVA, REPUBLIC OF";
         this.§^"?§["MC"] = "MONACO";
         this.§^"?§["MN"] = "MONGOLIA";
         this.§^"?§["ME"] = "MONTENEGRO";
         this.§^"?§["MS"] = "MONTSERRAT";
         this.§^"?§["MA"] = "MOROCCO";
         this.§^"?§["MZ"] = "MOZAMBIQUE";
         this.§^"?§["MM"] = "MYANMAR";
         this.§^"?§["NA"] = "NAMIBIA";
         this.§^"?§["NR"] = "NAURU";
         this.§^"?§["NP"] = "NEPAL";
         this.§^"?§["NL"] = "NETHERLANDS";
         this.§^"?§["NC"] = "NEW CALEDONIA";
         this.§^"?§["NZ"] = "NEW ZEALAND";
         this.§^"?§["NI"] = "NICARAGUA";
         this.§^"?§["NE"] = "NIGER";
         this.§^"?§["NG"] = "NIGERIA";
         this.§^"?§["NU"] = "NIUE";
         this.§^"?§["NF"] = "NORFOLK ISLAND";
         this.§^"?§["MP"] = "NORTHERN MARIANA ISLANDS";
         this.§^"?§["NO"] = "NORWAY";
         this.§^"?§["OM"] = "OMAN";
         this.§^"?§["PK"] = "PAKISTAN";
         this.§^"?§["PW"] = "PALAU";
         this.§^"?§["PS"] = "PALESTINE, STATE OF";
         this.§^"?§["PA"] = "PANAMA";
         this.§^"?§["PG"] = "PAPUA NEW GUINEA";
         this.§^"?§["PY"] = "PARAGUAY";
         this.§^"?§["PE"] = "PERU";
         this.§^"?§["PH"] = "PHILIPPINES";
         this.§^"?§["PN"] = "PITCAIRN";
         this.§^"?§["PL"] = "POLAND";
         this.§^"?§["PT"] = "PORTUGAL";
         this.§^"?§["PR"] = "PUERTO RICO";
         this.§^"?§["QA"] = "QATAR";
         this.§^"?§["RE"] = "RÉUNION";
         this.§^"?§["RO"] = "ROMANIA";
         this.§^"?§["RU"] = "RUSSIAN FEDERATION";
         this.§^"?§["RW"] = "RWANDA";
         this.§^"?§["BL"] = "SAINT BARTHÉLEMY";
         this.§^"?§["SH"] = "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA";
         this.§^"?§["KN"] = "SAINT KITTS AND NEVIS";
         this.§^"?§["LC"] = "SAINT LUCIA";
         this.§^"?§["MF"] = "SAINT MARTIN (FRENCH PART)";
         this.§^"?§["PM"] = "SAINT PIERRE AND MIQUELON";
         this.§^"?§["VC"] = "SAINT VINCENT AND THE GRENADINES";
         this.§^"?§["WS"] = "SAMOA";
         this.§^"?§["SM"] = "SAN MARINO";
         this.§^"?§["ST"] = "SAO TOME AND PRINCIPE";
         this.§^"?§["SA"] = "SAUDI ARABIA";
         this.§^"?§["SN"] = "SENEGAL";
         this.§^"?§["RS"] = "SERBIA";
         this.§^"?§["SC"] = "SEYCHELLES";
         this.§^"?§["SL"] = "SIERRA LEONE";
         this.§^"?§["SG"] = "SINGAPORE";
         this.§^"?§["SX"] = "SINT MAARTEN (DUTCH PART)";
         this.§^"?§["SK"] = "SLOVAKIA";
         this.§^"?§["SI"] = "SLOVENIA";
         this.§^"?§["SB"] = "SOLOMON ISLANDS";
         this.§^"?§["SO"] = "SOMALIA";
         this.§^"?§["ZA"] = "SOUTH AFRICA";
         this.§^"?§["GS"] = "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS";
         this.§^"?§["SS"] = "SOUTH SUDAN";
         this.§^"?§["ES"] = "SPAIN";
         this.§^"?§["LK"] = "SRI LANKA";
         this.§^"?§["SD"] = "SUDAN";
         this.§^"?§["SR"] = "SURINAME";
         this.§^"?§["SJ"] = "SVALBARD AND JAN MAYEN";
         this.§^"?§["SZ"] = "SWAZILAND";
         this.§^"?§["SE"] = "SWEDEN";
         this.§^"?§["CH"] = "SWITZERLAND";
         this.§^"?§["SY"] = "SYRIAN ARAB REPUBLIC";
         this.§^"?§["TW"] = "TAIWAN, PROVINCE OF CHINA";
         this.§^"?§["TJ"] = "TAJIKISTAN";
         this.§^"?§["TZ"] = "TANZANIA, UNITED REPUBLIC OF";
         this.§^"?§["TH"] = "THAILAND";
         this.§^"?§["TL"] = "TIMOR-LESTE";
         this.§^"?§["TG"] = "TOGO";
         this.§^"?§["TK"] = "TOKELAU";
         this.§^"?§["TO"] = "TONGA";
         this.§^"?§["TT"] = "TRINIDAD AND TOBAGO";
         this.§^"?§["TN"] = "TUNISIA";
         this.§^"?§["TR"] = "TURKEY";
         this.§^"?§["TM"] = "TURKMENISTAN";
         this.§^"?§["TC"] = "TURKS AND CAICOS ISLANDS";
         this.§^"?§["TV"] = "TUVALU";
         this.§^"?§["UG"] = "UGANDA";
         this.§^"?§["UA"] = "UKRAINE";
         this.§^"?§["AE"] = "UNITED ARAB EMIRATES";
         this.§^"?§["GB"] = "UNITED KINGDOM";
         this.§^"?§["US"] = "UNITED STATES";
         this.§^"?§["UM"] = "UNITED STATES MINOR OUTLYING ISLANDS";
         this.§^"?§["UY"] = "URUGUAY";
         this.§^"?§["UZ"] = "UZBEKISTAN";
         this.§^"?§["VU"] = "VANUATU";
         this.§^"?§["VE"] = "VENEZUELA, BOLIVARIAN REPUBLIC OF";
         this.§^"?§["VN"] = "VIET NAM";
         this.§^"?§["VG"] = "VIRGIN ISLANDS, BRITISH";
         this.§^"?§["VI"] = "VIRGIN ISLANDS, U.S.";
         this.§^"?§["WF"] = "WALLIS AND FUTUNA";
         this.§^"?§["EH"] = "WESTERN SAHARA";
         this.§^"?§["YE"] = "YEMEN";
         this.§^"?§["ZM"] = "ZAMBIA";
         this.§^"?§["ZW"] = "ZIMBABWE";
      }
      
      public static function §3!]§() : §8J§
      {
         if(§2!Q§ == null)
         {
            §2!Q§ = new §8J§();
         }
         return §2!Q§;
      }
      
      public function §9#q§(param1:String) : String
      {
         return this.§^"?§[param1];
      }
   }
}
